import Head from 'next/head'
import {usePageLoading} from "@/hooks/usePageLoading";
import Loader from "@/components/Loader";
import MainPage from "@/components/MainPage";

export default function Home() {
	
	const { isPageLoading } = usePageLoading();
	
	return (
		<>
			<Head>
				<title>Game сatalog</title>
				<meta name="description" content="Generated by create next app"/>
				<meta name="viewport" content="width=device-width, initial-scale=1"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>
				{isPageLoading ? (<Loader fullScreen/>) : (<MainPage/>)}
		</>
	)
}
